name: Deploy to servers

on:
  push:
    branches: [develop]

env:
  GITHUB: yes


jobs:

  send:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version-file: go.mod

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: $(go env GOPATH)/bin/staticcheck ./...

    - name: Run tests
      run: go test -race -vet=off ./...